### ISSUE TITLE
Expose some settings via JSON to ajax requests 

### ISSUE THREAD

**Issue by JonVisc** [AndrewMohawk/Aurora#6]
I am developing a Homebridge plugin to work alongside your project.

[homebridge-ambient-lights-aurora](https://github.com/JonVisc/homebridge-ambient-lights-aurora)

Right now it is hard to grab certain statuses from the project.  Luckily it is easy for statuses to be set as I use the AJAX calls you already set up, but ideally these things could be exposed to let the user know statuses of Aurora:

A `/ping` endpoint so I can tell the user if the Aurora service is running and is able to be controlled
A JSON GET `/loaded_configuration` endpoint for certain settings:
```
{
    auroraEnabled: true, //This would be a lightbulb switch on Homekit,
    loadedExtension: 'Aurora_Ambient_AutoCrop', //This is a list of states you could put a switch in for the different modes
}
```

I think those are the basics right now.  I'm sure I could send a pull request along with the basics but python isn't my forte, though I have dabbled in the past and could probably figure it out.

Thoughts?

**Comment by AndrewMohawk** [comment]
Hey @JonVisc , this sounds like a great idea. If you can give me a full list of the endpoints you are looking for and suggested responses I can definitely cook this up for you!

**Comment by JonVisc** [comment]
GET `/ping`
Response:

```
{
    version: '0.42-catsdontlikefireworks'
}
```
I know with all node projects it would be whatever the version is in the package.json file but maybe in this case it's whatever the VERSION file has inside it? 🤷‍♂️
But realistically when I request this if I get back a HTTP Code 200 then I would know the service is up.  Anything else, I could report to HomeKit that the service is not running.


GET `/loaded_configuration` (or `/loaded_config`)
```
{
    auroraEnabled: true, //This is: https://github.com/AndrewMohawk/Aurora/blob/master/config.ini.bak#L5
    loadedExtension: 'Aurora_Ambient_AutoCrop', //This is: https://github.com/AndrewMohawk/Aurora/blob/master/config.ini.bak#L15
}
```
This would be used upon load or HomeKit check to ensure that the visuals in HomeKit are correct.  Any other settings that would be valuable?  Maybe the `AURORA_DARKTHRESHOLD` as "brightness" but I'm not sure if that would confuse people.

I also have another discussion point but I'll add that in a different comment below.

**Comment by JonVisc** [comment]
I actually added a feature request to my project of stuff a bit more down the line but realized as I typed it up that it wouldn't impact this project at all, just how I expose things in this project via the plugin.

https://github.com/JonVisc/homebridge-ambient-lights-aurora/issues/1

**Comment by AndrewMohawk** [comment]
I've changed this to be one call to /status/ in https://github.com/AndrewMohawk/Aurora/pull/7 output example:

```
{ 
"enabled": True, 
"current_extension": "Aurora Ambient Lighting ( AutoCrop )", 
"current_extension_class": "Aurora_Ambient_AutoCrop", 
"current_version": "0.42-catsdontlikefireworks" 
}
```
